- id: elisp-lint
  name: Run Emacs elisp-lint
  description: Run all the elisp-lint checks
  entry: elisp-lint-batch.el
  language: script
  files: '\.el$'
  require_serial: true

# TODO: A dirty hack for the byte-compilation artifacts produced by
# the elisp-lint hook.  It would be wise to consider
# a different approach.
- id: elisp-lint-cleanup
  name: byte-compile clean-up
  description: Cleanup after elisp-lint
  language: system
  entry: "env -u GIT_LITERAL_PATHSPECS git clean -f '*.elc' '*-autoloads.el*'"
  pass_filenames: false
